POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "author": "abcder",
    "url": "google.com"
}

###
GET http://localhost:3003/api/blogs

###

DELETE http://localhost:3003/api/blogs/625605d2b88c25bd25ca9e15

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "whitemask",
    "name": "varre",
    "password": "nomaidens"
}


###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "url": "yahoo.com",
    "title": "abcdefg",
    "author": "qwerty",
    "likes": 5000,
    "userId": "625482b66e130878ab032fb1"
}